def get_cidades_atendidas():
    return {
        'PARNAIBA':'Teresina-PI',

        'SAO JOAO DA SERRA':'Teresina-PI',
        'OLHO D’ÁGUA DO PIAUI': 'Teresina-PI',
        'PAÇO LUMIAR': 'São Luís- MA',
        'PADRE MARCOS': 'Picos-PI',
        'PAES LANDIM': 'Picos-PI',
        'PAJEÚ DO PIAUI': 'Picos-PI',
        'PALMEIRA DO PIAUI': 'Picos-PI',
        'PALMEIRAIS': 'Teresina-PI',
        'PAQUETÁ': 'Picos-PI',
        'PARAIBANO': 'Picos-PI',
        'PARNAGUÁ': 'Picos-PI',
        'PARNAÍBA': 'Teresina-PI',
        'PARNARAMA': 'Teresina-PI',
        'PASSAGEM FRANCA': 'Teresina-PI',
        'PASSAGEM FRANCA': 'Picos-PI',
        'PASTOS BONS': 'Picos-PI',
        'PATOS DO PIAUI': 'Picos-PI',
        'PAULISTANA': 'Picos-PI',
        'PAULO RAMOS': 'Bacabal-MA',
        'PAVUSSÚ': 'Picos-PI',
        'PEDREIRAS': 'Bacabal-MA',
        'PEDRO II': 'Teresina-PI',
        'PEDRO LAURENTINO': 'Picos-PI',
        'PERITORÓ': 'Bacabal-MA',
        'PIMENTEIRAS': 'Picos-PI',
        'PINDARÉ MIRIM': 'Bacabal-MA',
        'PIO IX': 'Picos-PI',
        'PIO XII': 'Bacabal-MA',
        'PIRACURUCA': 'Teresina-PI',
        'PIRIPIRI': 'Teresina-PI',
        'PORTO': 'Teresina-PI',
        'PRATA DO PIAUI': 'Teresina-PI',
        'PRESIDENTE DUTRA': 'Bacabal-MA',
        'QUEIMADA NOVA': 'Picos-PI',
        'R.G.DO PIAUI': 'Picos-PI',
        'RAPOSA': 'São Luís- MA',
        'REDENÇÃO GURGUEIA': 'Picos-PI',
        'REGENERACAO': 'Teresina-PI',
        'RIBEIRA DO PIAUI': 'Picos-PI',
        'RIO GRANDE DO PIAUI': 'Picos-PI',
        'ROSÁRIO': 'São Luís- MA',
        'S. FRANCISCO DE ASSIS': 'Picos-PI',
        'S.A DOS LOPES': 'Bacabal-MA',
        'S.JOAO DOS PATOS': 'Picos-PI',
        'S.MIGUEL DO TAPUIO': 'Teresina-PI',
        'SANTA CRUZ DO PIAUI': 'Picos-PI',
        'SANTA CRUZ MILAGRES': 'Picos-PI',
        'SANTA INÊS': 'Bacabal-MA',
        'SANTA LUZ': 'Picos-PI',
        'SANTA LUZIA DO TIDE': 'Bacabal-MA',
        'SANTA MARIA CODIPI': 'Teresina-PI',
        'SANTA QUITÉRIA': 'Teresina-PI',
        'SANTA RITA': 'São Luís- MA',
        'SANTA ROSA DO PIAUI': 'Picos-PI',
        'SANTANA DO PIAUI': 'Picos-PI',
        'SANTO ANT. DE LISBOA': 'Picos-PI',
        'SANTO ANTONIO DOS': 'Teresina-PI',
        'SANTO ANTONIO LOPES': 'Bacabal-MA',
        'SANTO INÁCIO DO PIAUI': 'Picos-PI',
        'SAO BERNARDO': 'Teresina-PI',
        'SAO BRAS DO PIAUI': 'Picos-PI',
        'SAO FCO MARANHAO': 'Teresina-PI',
        'SAO FELIX DO PIAUÍ': 'Teresina-PI',
        'SÃO FELIX DO PIAUI': 'Picos-PI',
        'SAO FRANCISCO DO PIAUI': 'Picos-PI',
        'SÃO GONÇALO DO PIAUI': 'Teresina-PI',
        'SAO GONÇALO GURGUEIA': 'Picos-PI',
        'SÃO JOAO CANABRAVA': 'Picos-PI',
        'SÃO JOÃO DA FRONTEIRA': 'Teresina-PI',
        'SÃO JOÃO DA SERRA': 'Teresina-PI',
        'SÃO JOÃO DA VARJOTA': 'Picos-PI',
        'SÃO JOÃO DE': 'Picos-PI',
        'SÃO JOÃO DO ARRAIAL': 'Teresina-PI',
        'SÃO JOÃO DO PIAUI': 'Picos-PI',
        'SÃO JOÃO DO SOTER': 'Teresina-PI',
        'SÃO JOSÉ DO DIVINO': 'Teresina-PI',
        'SÃO JOSÉ DO PEIXE': 'Picos-PI',
        'SÃO JOSÉ DO PIAUI': 'Picos-PI',
        'SÃO JOSÉ RIBAMAR': 'São Luís- MA',
        'SAO JULIÃO': 'Picos-PI',
        'SAO LOURENÇO DO PIAUÍ': 'Picos-PI',
        'SÃO LUIS – MA': 'São Luís- MA',
        'SAO LUIS DO PIAUI': 'Picos-PI',
        'SÃO LUIS GONZAGA': 'Bacabal-MA',
        'SÃO MATEUS - DO': 'Bacabal-MA',
        'SAO MIGUEL B. GRANDE': 'Picos-PI',
        'SAO MIGUEL FIDALGO': 'Picos-PI',
        'SAO PEDRO DO PIAUI': 'Teresina-PI',
        'SAO R. NONATO': 'Picos-PI',
        'SAO RAIMUN. NONATO': 'Picos-PI',
        'SATUBINHA': 'Bacabal-MA',
        'SEBASTIÃO LEAL': 'Picos-PI',
        'SIGEFREDO PACHECO': 'Teresina-PI',
        'SIMÕES': 'Picos-PI',
        'SIMPLICIO MENDES': 'Picos-PI',
        'SOCORRO DO PIAUI': 'Picos-PI',
        'SUCUPIRA DO NORTE': 'Picos-PI',
        'SUCUPIRA DO RIACHÃO': 'Picos-PI',
        'SUSSUAPARA': 'Picos-PI',
        'TAMBORIL DO PIAUI': 'Picos-PI',
        'TANQUE DO PIAUI': 'Picos-PI',
        'TIMBIRAS': 'Bacabal-MA',
        'TIMON': 'Teresina-PI',
        'CURRALINHOS': 'Teresina-PI',
        'D. EXPEDITO LOPES': 'Picos-PI',
        'DEMERVAL LOBAO': 'Teresina-PI',
        'DIRCEU ARCOVERDE': 'Picos-PI',
        'DOM INOCENCIO': 'Picos-PI',
        'DOM PEDRO': 'Bacabal-MA',
        'DOMINGOS MOURAO': 'Teresina-PI',
        'DUQUE BACELAR': 'Teresina-PI',
        'ELESBÃO VELOSO': 'Picos-PI',
        'ELISEU MARTINS': 'Picos-PI',
        'ELIZEU MARTINS': 'Picos-PI',
        'ESPERANTINA': 'Teresina-PI',
        'FARTURA DO PIAUI': 'Picos-PI',
        'FLORES': 'Picos-PI',
        'FLORES DO PIAUI': 'Picos-PI',
        'FLORESTA DO PIAUÍ': 'Picos-PI',
        'FLORIANO': 'Picos-PI',
        'FRANCINÓPOLIS': 'Picos-PI',
        'FRANCISCO AIRES': 'Picos-PI',
        'FRANCISCO MACEDO': 'Picos-PI',
        'FRANCISCO SANTOS': 'Picos-PI',
        'FRONTEIRAS': 'Picos-PI',
        'GATURIANO': 'Picos-PI',
        'GEMINIANO': 'Picos-PI',
        'GILBUÉS': 'Picos-PI',
        'GOV. NEWTON BELO': 'Bacabal-MA',
        'GUADALUPE': 'Picos-PI',
        'GUADALUPE': 'Picos-PI',
        'GUARIBAS': 'Picos-PI',
        'HUGO NAPOLEAO': 'Teresina-PI',
        'IGARAPÉ GRANDE': 'Bacabal-MA',
        'ILHA GRANDE': 'Teresina-PI',
        'INDEPENDÊNCIA': 'Bacabal-MA',
        'INHUMA': 'Picos-PI',
        'IPIRANGA': 'Picos-PI',
        'ISAIAS COELHO': 'Picos-PI',
        'ITAINÓPOLIS': 'Picos-PI',
        'ITAPECURÚ MIRIM': 'São Luís- MA',
        'ITAUEIRA': 'Picos-PI',
        'ITAUEIRA': 'Picos-PI',
        'JACOBINA DO PIAUI': 'Picos-PI',
        'JAICÓS': 'Picos-PI',
        'JARDIM DO MULATO': 'Teresina-PI',
        'JATOBÁ DO PIAUI': 'Teresina-PI',
        'JERUMENHA': 'Picos-PI',
        'JOÃO COSTA': 'Picos-PI',
        'JOAQUIM PIRES': 'Teresina-PI',
        'JOSE DE FREITAS': 'Teresina-PI',
        'JUAZEIRO DO PIAUI': 'Teresina-PI',
        'JÚLIO BORGES': 'Picos-PI',
        'JUREMA': 'Picos-PI',
        'LAGO DA PEDRA': 'Bacabal-MA',
        'LAGO DO JUNCO': 'Bacabal-MA',
        'LAGO DOS RODRIGUES': 'Bacabal-MA',
        'LAGO VERDE': 'Bacabal-MA',
        'LAGOA ALEGRE': 'Teresina-PI',
        'LAGOA DE S. FCO': 'Teresina-PI',
        'LAGOA DO BARRO': 'Picos-PI',
        'LAGOA DO PIAUÍ': 'Teresina-PI',
        'LAGOA DO SÍTIO': 'Picos-PI',
        'LAGOINHA DO PIAUI': 'Teresina-PI',
        'LANDRI SALES': 'Picos-PI',
        'LIMA CAMPOS': 'Bacabal-MA',
        'LIMA CAMPOS': 'Bacabal-MA',
        'LUIS CORREIA': 'Teresina-PI',
        'LUZILANDIA': 'Teresina-PI',
        'MADEIRO': 'Teresina-PI',
        'MAGALHAES ALMEIDA –': 'Teresina-PI',
        'MANOEL EMIDIO': 'Picos-PI',
        'MANOEL EMÍDIO': 'Picos-PI',
        'MARCOLÂNDIA': 'Picos-PI',
        'MARCOS PARENTE': 'Picos-PI',
        'MASSAPÊ DO PIAUI': 'Picos-PI',
        'MATA ROMA': 'Teresina-PI',
        'MATA ROMA': 'Teresina-PI',
        'MATIAS OLIMPIO': 'Teresina-PI',
        'MATIAS OLIMPIO': 'Teresina-PI',
        'MATÕES': 'Teresina-PI',
        'MIGUEL ALVES': 'Teresina-PI',
        'MIRANDA DO NORTE': 'São Luís- MA',
        'MONSENHOR GIL': 'Teresina-PI',
        'MONSENHOR HIPÓLITO': 'Picos-PI',
        'MONTE ALEGRE': 'Picos-PI',
        'MONTE ALEGRE PIAUI': 'Picos-PI',
        'MORRO DO CHAPEU PIAUI': 'Teresina-PI',
        'MURICI DOS PORTELAS': 'Teresina-PI',
        'N. SENHORA REMEDIOS': 'Teresina-PI',
        'NAZARÉ DO PIAUI': 'Picos-PI',
        'NAZARÉ DO PIAUI': 'Picos-PI',
        'NAZÁRIA': 'Teresina-PI',
        'NOSSA SENHORA DE': 'Teresina-PI',
        'NOVA SANTA RITA': 'Picos-PI',
        'NOVO ORIENTE PIAUI': 'Picos-PI',
        'NOVO SANTO ANTONIO': 'Teresina-PI',
        'OEIRAS': 'Picos-PI',
        'OLHO D’AGUA CUNHAS': 'Bacabal-MA',
        'ACAUÃ': 'Picos-PI',
        'AGRICOLÂNDIA': 'Teresina-PI',
        'AGUA BRANCA': 'Teresina-PI',
        'ALAGOINHA DO PIAUÍ': 'Picos-PI',
        'ALDEIAS ALTAS': 'Teresina-PI',
        'ALEGRETE PIAUI': 'Picos-PI',
        'ALTO ALEGRE': 'Bacabal-MA',
        'ALTO LONGA': 'Teresina-PI',
        'ALTOS': 'Teresina-PI',
        'ALVOR. GURGUEIA': 'Picos-PI',
        'AMARANTE DO PIAUÍ': 'Teresina-PI',
        'ANAPURUS': 'Teresina-PI',
        'ANISIO DE ABREU': 'Picos-PI',
        'ANTONIO ALMEIDA': 'Picos-PI',
        'ARAIOSES': 'Teresina-PI',
        'AROAZES': 'Picos-PI',
        'AROEIRA DO ITAIM': 'Picos-PI',
        'ARRAIAL': 'Picos-PI',
        'AVELINO LOPES': 'Picos-PI',
        'BACABAL': 'Bacabal-MA',
        'BACABEIRA': 'Bacabal-MA',
        'BAIXA GRANDE DO': 'Picos-PI',
        'BARRA D’ALCÂNTARA': 'Picos-PI',
        'BARRAS': 'Teresina-PI',
        'BARREIRAS': 'Picos-PI',
        'BARRO DURO': 'Teresina-PI',
        'BATALHA': 'Teresina-PI',
        'BELA VISTA DO': 'Bacabal-MA',
        'BELA VISTA PIAUI': 'Picos-PI',
        'BELÉM DO PIAUI': 'Picos-PI',
        'BENEDITINOS': 'Teresina-PI',
        'BERTOLINIA': 'Picos-PI',
        'BETANIA DO PIAUI': 'Picos-PI',
        'BOA HORA': 'Teresina-PI',
        'BOCAINA': 'Picos-PI',
        'BOM JARDIM': 'Bacabal-MA',
        'BOM JESUS': 'Picos-PI',
        'BOM LUGAR': 'Bacabal-MA',
        'BOM PRINCIPIO': 'Teresina-PI',
        'BONFIM DO PIAUI': 'Picos-PI',
        'BOQUEIRAO DO PIAUI': 'Teresina-PI',
        'BR.DE GRAJAÚ-MA': 'Picos-PI',
        'BRASILEIRA': 'Teresina-PI',
        'BREJO': 'Teresina-PI',
        'BREJO DE AREIA': 'Bacabal-MA',
        'BREJO DO PIAUI': 'Picos-PI',
        'BURITI BRAVO': 'Teresina-PI',
        'BURITI DOS LOPES': 'Teresina-PI',
        'BURITI DOS MONTES': 'Teresina-PI',
        'C. ALEGRE FIDALGO': 'Picos-PI',
        'C. GRANDE PIAUI': 'Picos-PI',
        'CABECEIRA PIAUI': 'Teresina-PI',
        'CAJAZEIRAS PIAUI': 'Picos-PI',
        'CAJUEIRO DA PRAIA': 'Teresina-PI',
        'CALDEIRAO GRANDE': 'Picos-PI',
        'CAMPINAS DO PIAUI': 'Picos-PI',
        'CAMPO LARGO': 'Teresina-PI',
        'CAMPO MAIOR': 'Teresina-PI',
        'CANAVIEIRA': 'Picos-PI',
        'CANTO DO BURITI': 'Picos-PI',
        'CAP.GERV.OLIVEIRA': 'Picos-PI',
        'CAPINZAL DO NORTE': 'Bacabal-MA',
        'CAPITÃO DE CAMPOS': 'Teresina-PI',
        'CARACOL': 'Picos-PI',
        'CARIDADE DO PIAUI': 'Picos-PI',
        'CASTELO DO PIAUI': 'Teresina-PI',
        'CAXIAS': 'Teresina-PI',
        'CAXINGÓ': 'Teresina-PI',
        'CAXUXA': 'Bacabal-MA',
        'CHAPADINHA': 'Teresina-PI',
        'COCAL': 'Teresina-PI',
        'COCAL DE TELHA': 'Teresina-PI',
        'COCAL DOS ALVES': 'Teresina-PI',
        'CODÓ': 'Bacabal-MA',
        'COELHO NETO': 'Teresina-PI',
        'COIVARAS': 'Teresina-PI',
        'COL.DE GURGUEIA': 'Picos-PI',
        'COLONIA DE GURGUÉIA': 'Picos-PI',
        'COLONIA DO PIAUI': 'Picos-PI',
        'CONCEIÇÃO DO CANINDÉ': 'Picos-PI',
        'COROATÁ': 'Bacabal-MA',
        'CORONEL JOSE DIAS': 'Picos-PI',
        'CORRENTE': 'Picos-PI',
        'CRISTALÂNDIA': 'Picos-PI',
        'CRISTINO CASTRO': 'Picos-PI',
        'CURIMATÁ': 'Picos-PI',
        'TRIZIDELA DO VALE': 'Bacabal-MA',
        'TUNTUN': 'Bacabal-MA',
        'TUTOIA': 'Teresina-PI',
        'UNIAO': 'Teresina-PI',
        'URUÇUI': 'Picos-PI',
        'VALENÇA': 'Picos-PI',
        'VARZEA BRANCA': 'Picos-PI',
        'VERA MENDES': 'Picos-PI',
        'VILA NOVA DO PIAUI': 'Picos-PI',
        'VITORINO FREIRE': 'Bacabal-MA',
        'WALL FERRAZ': 'Picos-PI',
        'ZÉ DOCA': 'Bacabal-MA',
        'TERESINA':'Teresina-PI'
    }